config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :jobs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, :description, presence: true
  has_many :tags
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :job
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new
  end

  def create
    Job.create(job_params)
    redirect_to jobs_path
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    @job.update_attributes(job_params)
    redirect_to jobs_path
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_path
  end

  def show
    @job = Job.find(params[:id])
  end

  private

  def job_params
    params.require(:job).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
  <div class="field">
    <%= f.label :title, class: 'label' %>
    <div class="field">
      <%= f.text_field :title, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :description, class: 'label' %>
    <div class="field">
      <%= f.text_area :description, size: '60x6', class: 'textarea' %>
    </div>
  </div>

  <div class="field">
    <%= f.submit class: 'button is-primary' %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<h3 class="title is-3"><%= job.title %></h3>
<p><%= job.description %></p>
<h5 class="title is-5"><%= link_to "Edit", edit_job_path(job) %></h5>
<h5 class="title is-5"><%= link_to "Delete", job, method: :delete %></h5>

app/views/jobs/_job_collection.html.erb
<h3 class="title is-3"><%= job.title %></h3>
<h5 class="title is-5"><%= link_to "Show", job_path(job) %></h5>

app/views/jobs/edit.html.erb
<%= render 'form' %>

app/views/jobs/index.html.erb
<h1 class="title is-1">Open Jobs</h1>

<%= render(partial: "job_collection",
           collection: @jobs,
           as: :job) || "There are no jobs available." %>

app/views/jobs/new.html.erb
<%= render 'form' %>

app/views/jobs/show.html.erb
<%= render @job %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar is-light" role="navigation" aria-label="dropdown navigation">
    <div class="navbar-menu">
      <div class="navbar-start">
        <%= link_to "Home", jobs_path, class: 'navbar-item' %>
      </div>
      <div class="navbar-end">
        <%= link_to "Add Job", new_job_path, class: 'navbar-item' %>
      </div>
    </div>
  </nav>
</header>